# -*- coding: utf-8 -*-
"""helloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xfigk7bRiBxH7kMBoKEMsK5Cnh9Ow038
"""

print("Hello World!")